EC_funding/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('total_funds_per_country/', views.total_funds_per_country, name='total_funds_per_country'),
    path('organisations/', views.organisations, name='organisations'),
    path('projects/', views.projects, name='projects'),
    path('', views.main, name='main'),
    path('projects/detail_project/<int:id>', views.detail_project, name='detail_project'),
    path('organisations/detail_organisation/<int:id>', views.detail_organisation, name='detail_organisation'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SDU_exercise/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('EC_funding.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

EC_funding/models.py
from django.db import models
from django.utils import timezone

# Create the model for projects table
# note: created fileds even for colums that are currently empty, 
# in case they are needed later in the project
class Projects(models.Model):
    id = models.IntegerField(primary_key=True)
    acronym = models.CharField(max_length=30, null=True, blank=True)
    status = models.CharField(max_length=10, null=True, blank=True)
    title = models.TextField(null=True, blank=True)
    startDate = models.DateField(null=True, blank=True)
    endDate = models.DateField(null=True, blank=True)
    totalCost = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    ecMaxContribution = models.DecimalField(max_digits=13, decimal_places=2, blank=True, null=True)
    legalBasis= models.CharField(max_length=20, null=True, blank=True) 
    topics= models.CharField(max_length=60, null=True, blank=True) 
    ecSignatureDate = models.CharField(max_length=5, null=True, blank=True) 
    frameworkProgramme = models.CharField(max_length=50, null=True, blank=True)
    masterCall = models.CharField(max_length=5, null=True, blank=True)
    subCall = models.CharField(max_length=40, null=True, blank=True)
    fundingScheme = models.CharField(max_length=20, null=True, blank=True)
    nature = models.CharField(max_length=30, null=True, blank=True)
    objective = models.TextField(null=True, blank=True)
    contentUpdateDate = models.DateTimeField(null=True, blank=True)
    rcn = models.IntegerField(null=True, blank=True)
    grantDoi = models.CharField(max_length=255, null=True, blank=True)
    
    # this will help identify the model later, e.g. in error messages
    def __str__(self):
        return self.acronym


# Create the model for organisations table
# note: created fileds even for colums that are currently empty, 
# in case they are needed later in the project
class Organisations(models.Model):
    project = models.ForeignKey(Projects, on_delete=models.CASCADE)
    projectAcronym = models.CharField(max_length=30, null=True, blank=True)
    organisationID = models.FloatField(null=True, blank=True)
    vatNumber = models.CharField(max_length=20, null=True, blank=True)
    name = models.TextField(null=True, blank=True)
    shortName = models.TextField(null=True, blank=True)
    SME = models.CharField(max_length=3, null=True, blank=True); 
    activityType = models.CharField(max_length=3, null=True, blank=True)
    street = models.TextField(null=True, blank=True)
    postCode = models.CharField(max_length=30, null=True, blank=True)
    city = models.TextField(null=True, blank=True)
    country = models.CharField(max_length=30, null=True, blank=True)
    nutsCode = models.CharField(max_length=30, null=True, blank=True)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    organizationURL = models.URLField()
    contactForm = models.URLField()
    contentUpdateDate = models.DateTimeField(null=True, blank=True)
    rcn = models.FloatField(null=True, blank=True)
    order = models.FloatField(null=True, blank=True)
    role = models.CharField(max_length=15, null=True, blank=True)
    ecContribution = models.FloatField(null=True, blank=True)
    netEcContribution = models.FloatField(null=True, blank=True)
    totalCost = models.FloatField( null=True, blank=True)
    endOfParticipation = models.BooleanField(null=True, blank=True)
    active = models.BooleanField(null=True, blank=True)
    
    # this will help identify the model later, e.g. in error messages
    def __str__(self):
        return self.shortName

EC_funding/views.py
from django.http import HttpResponse
from django.template import loader
from .models import Organisations
from .models import Projects
from django.core.paginator import Paginator
from django.core.paginator import PageNotAnInteger
from django.core.paginator import EmptyPage
from django.shortcuts import render
from django.db.models import Sum, F

# next two lines prevent matplot lib from trying to graphically display the plot and avoid some error msgs
import matplotlib as mpl
mpl.use('Agg')

import matplotlib.pyplot as plt
from django.db.models.functions import Coalesce
from decimal import Decimal
from django.db.models import F, Case, When

def main(request):
  template = loader.get_template('main.html')
  return HttpResponse(template.render())

def organisations(request):

    # select onlt the unique organisations, based on the organisationID
    myorganisations = Organisations.objects.all().values().order_by('name').distinct('name')

    # use paginator to display 100 organisations at the time 
    paginator = Paginator(myorganisations, 100)
    page = request.GET.get('page')
    try:
        organisations = paginator.page(page)
    except PageNotAnInteger:
        organisations = paginator.page(1)
    except EmptyPage:
        organisations = paginator.page(paginator.num_pages) 

    return render(request, 'all_organisations.html', {'organisations': organisations})


def projects(request):

    myprojects = Projects.objects.all().values().order_by('acronym')

    # use paginator to display 100 projects at the time 
    paginator = Paginator(myprojects, 100)
    page = request.GET.get('page')
    try:
        projects = paginator.page(page)
    except PageNotAnInteger:
        projects = paginator.page(1)
    except EmptyPage:
        projects = paginator.page(paginator.num_pages) 

    return render(request, 'all_projects.html', {'projects': projects})

def detail_project(request, id):
  myproject = Projects.objects.get(id=id)
  template = loader.get_template('detail_project.html')
  context = {
    'myproject': myproject,
  }
  return HttpResponse(template.render(context, request))

def detail_organisation(request, id):
  myorganisation = Organisations.objects.get(id=id)
  template = loader.get_template('detail_organisation.html')
  context = {
    'myorganisation': myorganisation,
  }
  return HttpResponse(template.render(context, request))

def total_funds_per_country(request):
    # Query the database to get the total amount of funds per country
    # as there are too many countries, sort it and take only top 10 to plot 
    num_cuntries_to_plot = 10
    funds_per_country = Organisations.objects.exclude(ecContribution=Decimal('NaN')).values('country').annotate(total_funds=Sum('ecContribution')).order_by('-total_funds')[:num_cuntries_to_plot]
    
    # Extract the country names and total funds from the queryset
    countries = [item['country'] for item in funds_per_country]
    funds = [item['total_funds'] for item in funds_per_country]

    # Some quick prints to check what's going on...  
    # print (top_10_funds_per_country)
    # print (countries)
    # print (funds)
    # unique_countries = Organisations.objects.exclude(ecContribution=Decimal('NaN')).values_list('country', flat=True).distinct()
    # print(unique_countries)
    # number_of_countries = Organisations.objects.exclude(ecContribution=Decimal('NaN')).values_list('country', flat=True).distinct().count()
    # print(number_of_countries)

    # Create the bar chart
    plt.bar(countries, funds)

    # Add labels to the x and y axes
    plt.xlabel('Country')
    plt.ylabel('Total Funds (in €)')

    # Save the plot to a file
    plt.savefig('media/total_funds_per_country.png')

    # plt.bar(countries, funds).savefig('total_funds_per_country.png')

    # Render the template and pass the file name to it
    return render(request, 'plot_funding.html', {'plot': 'total_funds_per_country.png'})

EC_funding/templates/all_organisations.html
<!DOCTYPE html>
<html>
<body>

<h1>Organisations</h1>
 
<p><a href="/">Return HOME</a></p>


<div class="pagination">
  {% if organisations.has_previous %}
      <a href="?page={{ organisations.previous_page_number }}">previous</a>
  {% endif %}
  <span class="current-page">Page {{ organisations.number }} of {{ organisations.paginator.num_pages }}</span>
  {% if organisations.has_next %}
      <a href="?page={{ organisations.next_page_number }}">next</a>
  {% endif %}
</div>

<ul>
  {% for x in organisations %}
    <li><a href="detail_organisation/{{ x.id }}"> details </a>{{ x.name }}, {{ x.country }}</li>
  {% endfor %}
</ul>

<!-- 
<ul>
  {% for x in myorganisations %}
    <li>{{ x.name }}, {{ x.country }}</li>
  {% endfor %}
</ul> -->

</body>
</html>

EC_funding/templates/all_projects.html
<!DOCTYPE html>
<html>
<body>

<h1>Projects</h1>
 
<p><a href="/">Return HOME</a></p>

<div class="pagination">
    {% if projects.has_previous %}
        <a href="?page={{ projects.previous_page_number }}">previous</a>
    {% endif %}
    <span class="current-page">Page {{ projects.number }} of {{ projects.paginator.num_pages }}</span>
    {% if projects.has_next %}
        <a href="?page={{ projects.next_page_number }}">next</a>
    {% endif %}
  </div>
  
  <ul>
    {% for x in projects %}
      <li> <a href="detail_project/{{ x.id }}">  details </a> {{ x.acronym }} -  {{ x.title }}</li>
    {% endfor %}
  </ul>

</body>
</html>

EC_funding/templates/detail_organisation.html
{% extends "master.html" %}

{% block title %}
  Details about {{ myorganisation.name }}
{% endblock %}


{% block content %}
    
    <h1>{{ myorganisation.name }}</h1>
    <h2>Full information </h2>

    <p><b>organisationID:</b> {{ myorganisation.id }}</p> 
    <p><b>vatNumber:</b> {{ myorganisation.vatNumber }}</p> 
    <p><b>name:</b> {{ myorganisation.name }}</p> 
    <p><b>shortName:</b> {{ myorganisation.shortName }}</p> 
    <p><b>SME:</b> {{ myorganisation.SME }}</p> 
    <p><b>activityType:</b> {{ myorganisation.activityType }}</p> 
    <p><b>street:</b> {{ myorganisation.street }}</p> 
    <p><b>postCode:</b> {{ myorganisation.postCode }}</p> 
    <p><b>city:</b> {{ myorganisation.city }}</p> 
    <p><b>country:</b> {{ myorganisation.country }}</p> 
    <p><b>latitude:</b> {{ myorganisation.latitude }}</p> 
    <p><b>longitude:</b> {{ myorganisation.longitude }}</p> 
    <p><b>organizationURL:</b> {{ myorganisation.organizationURL }}</p> 
    <p><b>contentUpdateDate:</b> {{ myorganisation.contentUpdateDate }}</p> 
    <p><b>objective:</b> {{ myorganisation.objective }}</p> 
    <p><b>rcn:</b> {{ myorganisation.rcn }}</p> 

<br>
<br>
<p>Back to <a href="/organisations">Organisations</a></p>
  
{% endblock %}

EC_funding/templates/detail_project.html
{% extends "master.html" %}

{% block title %}
  Details about {{ myproject.acronym }}
{% endblock %}


{% block content %}
  <h1>Project: {{ myproject.title }} </h1>
  <p></p>

  <h2>Organisations involved </h2>

{% for organisation in myproject.organisations_set.all %}

{{organisation.name}}<br>

{%endfor%}

<h2>Full information </h2>

<p><b>id:</b> {{ myproject.id }}</p> 
<p><b>acronym:</b> {{ myproject.acronym }}</p> 
<p><b>status:</b> {{ myproject.status }}</p> 
<p><b>Tititle:</b> {{ myproject.title }}</p> 
<p><b>startDate:</b> {{ myproject.startDate }}</p> 
<p><b>endDate:</b> {{ myproject.endDate }}</p> 
<p><b>totalCost:</b> {{ myproject.totalCost }}</p> 
<p><b>ecMaxContribution:</b> {{ myproject.ecMaxContribution }}</p> 
<p><b>legalBasis:</b> {{ myproject.legalBasis }}</p> 
<p><b>topics:</b> {{ myproject.topics }}</p> 
<p><b>ecSignatureDate:</b> {{ myproject.ecSignatureDate }}</p> 
<p><b>frameworkProgramme:</b> {{ myproject.frameworkProgramme }}</p> 
<p><b>masterCall:</b> {{ myproject.masterCall }}</p> 
<p><b>subCall:</b> {{ myproject.subCall }}</p> 
<p><b>nature:</b> {{ myproject.nature }}</p> 
<p><b>objective:</b> {{ myproject.objective }}</p> 
<p><b>contentUpdateDate:</b> {{ myproject.contentUpdateDate }}</p> 
<p><b>rcn:</b> {{ myproject.rcn }}</p> 
<p><b>grantDoi:</b> {{ myproject.grantDoi }}</p> 
<br>
<br>
<p>Back to <a href="/projects">Projects</a></p>
  
{% endblock %}

EC_funding/templates/main.html
{% extends "master.html" %}

{% block title %}
  EU FP7 data
{% endblock %}


{% block content %}
  <h1>SDU data on EU Projects from FP7</h1>

  <h2>Access the raw data</h1>

  <h3>Projects</h3>
  
  <p>See a list of all projects here: <a href="projects/">all projects</a></p>
  
  <h3>Organisations</h3>
  <p>See a list of all organisations here: <a href="organisations/">all organisations</a></p>

  <h1>Some analysis of the data</h1>
  <h3>Total funding</h3>

  <p></p>See a graph of the amount of funding received by the top 10 most funded countries 
  <a href="total_funds_per_country/"> here</a></p>

{% endblock %}

EC_funding/templates/master.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>

EC_funding/templates/plot_funding.html
<!DOCTYPE html>
<html>
<body>

    <h1>Top 10 most funded countries</h1>

    <img src="../media/{{ plot }}" alt="Total Funds per Country">

    <p><a href="/">Return HOME</a></p>


</body>
</html>